language: rust
sudo: false

os: linux
rust: stable

cache: cargo

before_script:
  - wget https://github.com/kpp/mdBook/releases/download/e2018/mdbook -P ~/.cargo/bin/ && chmod +x ~/.cargo/bin/mdbook

script:
  - mdbook build

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: false
  local_dir: book/html
  github_token: $GITHUB_API_KEY
  on:
    branch: master
